learning_blog/learning_blog/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from learning_blogs import views


urlpatterns = [
    path('admin/', admin.site.urls),
	path('learning_blogs/',include(('learning_blogs.urls','learning_blogs'), namespace=None)),
	path('myblog/', include(('myblog.urls', 'myblog'), namespace=None)),
	path('users/', include(('users.urls', 'users'), namespace=None)),
]

learning_blog/learning_blogs/urls.py
"""定义learning_blogs的URL模式"""
from django.urls import path, re_path
from . import views


app_name='learning_blogs'

urlpatterns = [
    #主页
    path('index/', views.index, name='index'),

    #显示所有标题
    re_path(r'^topics/$', views.topics, name='topics'),

    # 特定主题的详细页面
    re_path(r'^topics/(?P<topic_id>\d+)/$', views.topic, name='topic'),

    # 用于添加新主题的网页
    re_path(r'^new_topic/$', views.new_topic, name='new_topic'),

    # 用于添加新条目的页面
    re_path(r'^new_entry/(?P<topic_id>\d+)/$', views.new_entry, name='new_entry'),

    # 用于编辑条目的页面
    re_path(r'^edit_entry/(?P<entry_id>\d+)/$', views.edit_entry, name='edit_entry'),

]

learning_blog/users/urls.py
"""为应用程序users定义URL模式"""
from django.urls import path
from django.conf.urls import url,include,re_path
from django.contrib.auth.views import login

from . import views

app_name = "users"

urlpatterns = [


	#登录页面
	#path('login/', login, name='login'),
	re_path(r'^login/$', login, {'template_name': 'users/login.html'}, name='login'),

	#注销页面
	re_path(r'^logout/$', views.logout_view, name='logout'),

	#注册页面
	re_path(r'^register/$', views.register, name='register'),

]

learning_blog/learning_blogs/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Topic(models.Model):
	"""用户学习的主题"""
	text = models.CharField(max_length=200)
	date_added = models.DateTimeField(auto_now_add=True)

	#将数据关联到用户
	owner = models.ForeignKey(User,on_delete=models.CASCADE)
	
	def __str__(self):
		"""返回模型的字符串表示"""
		return self.text
	
class Entry(models.Model):
	"""学到的有关弄个主题的具体知识"""
	topic = models.ForeignKey(Topic,on_delete=models.CASCADE)
	text = models.TextField()
	date_added = models.DateTimeField(auto_now_add=True)
	
	class Meta:
		verbose_name_plural = 'entries'
		
	def __str__(self):
		"""返回模型的字符串表示"""
		if len(self.text)>50:
			return self.text[:50] + "..."
		else:
			return self.text

learning_blog/learning_blogs/forms.py
from django import forms
from .models import Topic,Entry

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = {'text'}
        labels = {'text':''}


class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = {'text'}
        labels = {'text':''}
        widgets = {'text': forms.Textarea(attrs={'cols':80})}

learning_blog/learning_blogs/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse,HttpResponseRedirect,Http404

#reverse提示错误，将下面的第一行代码换为第二个
#1、from django.core.urlresolvers import reverse
from django.urls import reverse

from .models import Topic,Entry
from .forms import TopicForm,EntryForm

#限制对topics 页面的访问
from django.contrib.auth.decorators import login_required


# Create your views here.

def index(request):
	"""学习笔记的主页"""
	return render(request,'learning_blogs/index.html')

"""限制对topics 页面的访问"""
@login_required
def topics(request):
	"""显示所有的主题"""
	#topics = Topic.objects.order_by('date_added')

	#只允许用户访问自己的主题
	topics = Topic.objects.filter(owner=request.user).order_by('date_added')


	context = {'topics':topics}
	return render(request,'learning_blogs/topics.html',context)


@login_required
def topic(request,topic_id):
	"""显示单个主题及其所有的条目"""
	topic = Topic.objects.get(id=topic_id)

	#确认请求的主题属于当前用户
	if topic.owner != request.user:
		raise Http404

	entries = topic.entry_set.order_by('-date_added')
	context = {'topic':topic, 'entries':entries}
	return render(request,'learning_blogs/topic.html',context)

def new_topic(request):
	"""添加新的主题"""
	if request.method != 'POST':
		#未提交数据，创建一个新表单
		form = TopicForm()
	else:
		#POST提交的数据，对数据进行处理
		form = TopicForm(request.POST)
		if form.is_valid():

			#form.save()

			#将新主题关联到当前用户
			new_topic = form.save(commit=False)
			new_topic.owner = request.user
			new_topic.save()

			return HttpResponseRedirect('/learning_blogs/topics')

	context = {'form':form}
	return render(request,'learning_blogs/new_topic.html',context)


@login_required
def new_entry(request,topic_id):

	"""在特定的主题中添加新条目"""
	topic = Topic.objects.get(id=topic_id)

	if request.method != 'POST':
		#未提交数据，创建一个新表单
		form = EntryForm()
	else:
		#POST提交的数据，对数据进行处理
		form = EntryForm(data=request.POST)

		if form.is_valid():
			new_entry = form.save(commit=False)
			new_entry.topic = topic

			# 确认请求的主题属于当前用户
			if topic.owner != request.user:
				raise Http404

			new_entry.save()

			#return HttpResponseRedirect('/learning_blogs/topics')
			#return redirect(reverse('/learning_blogs/topics', args=[topic_id]))
			return HttpResponseRedirect(reverse('learning_blogs:topic', args=[topic_id]))

	context = {'topic':topic, 'form':form}
	return render(request,'learning_blogs/new_entry.html',context)


@login_required
def edit_entry(request, entry_id):
	"""编辑既有条目"""
	entry = Entry.objects.get(id=entry_id)
	topic = entry.topic
	topic_id = topic.id

	# 确认请求属于当前用户
	if topic.owner != request.user:
		raise Http404

	if request.method != "POST":
		#初次请求，使用当前条目填充
		form = EntryForm(instance=entry)
	else:
		#Post提交数据，对数据进行处理
		form = EntryForm(instance=entry, data=request.POST)

		if form.is_valid():
			form.save()
			return HttpResponseRedirect(reverse('learning_blogs:topic', args=[topic_id]))
			#return HttpResponseRedirect(reverse('learning_blogs:topics'))


	context = {'entry':entry, 'topic':topic, 'form':form}
	return render(request,'learning_blogs/edit_entry.html',context)

learning_blog/learning_blogs/templates/learning_blogs/base.html
{% load bootstrap3 %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Learning Blog</title>

    {% bootstrap_css %}
    {% bootstrap_javascript %}

</head>
<body>

    <!-- Static navbar -->
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed"
                        data-toggle="collapse" data-target="#navbar"
                        aria-expanded="false" aria-controls="navbar">
                </button>
                <a class="navbar-brand" href="{% url 'learning_blogs:index' %}">
                    Learning Blog</a>
            </div>

            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'learning_blogs:topics' %}">Topics</a></li>
                </ul>

                <ul class="nav navbar-nav navbar-right">
                    {% if user.is_authenticated %}
                        <li><a>Hello, {{ user.username }}.</a></li>
                        <li><a href="{% url 'users:logout' %}">log out</a></li>
                    {% else %}
                        <li><a href="{% url 'users:register' %}">register</a></li>
                        <li><a href="{% url 'users:login' %}">log in</a></li>
                    {% endif %}
                </ul>
            </div>
            <!--/.nav-collapse -->
        </div>
    </nav>

    <div class="container">
        <div class="page-header">
            {% block header %}{% endblock header %}
        </div>

        <div>
            {% block content %}{% endblock content %}
        </div>
    </div>
    <!-- /container -->

</body>
</html>

learning_blog/learning_blogs/templates/learning_blogs/edit_entry.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Edit Entry</title>
</head>
<body>
{% extends "learning_blogs/base.html" %}

{% load bootstrap3 %}

{% block header %}
    <h2><a href="{% url 'learning_blogs:topic' topic.id %}">{{ topic }}</a></h2>
{% endblock header %}

{% block content %}

    <div class="panel panel-default">
            <div class="panel-heading">
                <h3>
                    Edit entry:
                </h3>
            </div>
            <div class="panel-body">
                <form action="{% url 'learning_blogs:edit_entry' entry.id %}" method="post">

                    {% csrf_token %}
                    {% bootstrap_form form %}

                    {% buttons %}
                        <button name="submit">save changes</button>
                    {% endbuttons %}
                </form>
            </div>
    </div> <!-- panel -->

{% endblock content %}
</body>
</html>

learning_blog/learning_blogs/templates/learning_blogs/index.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Index</title>
</head>
<body>

{% extends "learning_blogs/base.html" %}

{% block header %}
    <div class='jumbotron'>
        <h1>Track your learning.</h1>
    </div>
{% endblock header %}

{% block content %}

    <h2>
        <a href="{% url 'users:register' %}">Register an account</a> to make
    your own Learning Blog, and list the topics you're learning about.
    </h2>
    <h2>
        Whenever you learn something new about a topic, make an entry
        summarizing what you've learned.
    </h2>
{% endblock content %}

</body>
</html>



learning_blog/learning_blogs/templates/learning_blogs/new_entry.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>New Entry</title>
</head>
<body>
{% extends 'learning_blogs/base.html' %}

{% load bootstrap3 %}

{% block header %}
    <h2><a href="{% url 'learning_blogs:topic' topic.id %}">{{ topic }}</a></h2>
{% endblock header %}


{% block content %}

    <div class="panel panel-default">
            <div class="panel-heading">
                <h3>
                    Add a new Entry:
                </h3>
            </div>
            <div class="panel-body">
                <form action="{% url 'learning_blogs:new_entry' topic.id %}" method="post">

                    {% csrf_token %}
                    {% bootstrap_form form %}

                    {% buttons %}
                        <button name="submit">add entry</button>
                    {% endbuttons %}
                </form>
            </div>
    </div> <!-- panel -->

{% endblock content %}
</body>
</html>

learning_blog/learning_blogs/templates/learning_blogs/new_topic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>New Topic</title>
</head>
<body>
{% extends 'learning_blogs/base.html' %}
{% load bootstrap3 %}

{% block header %}
    <h2>Add a new topic: </h2>
{% endblock header %}

{% block content %}

    <form action="{% url 'learning_blogs:new_topic' %}" method="post">

        {% csrf_token %}
        {% bootstrap_form form %}

        {% buttons %}
            <button name="submit" class="btn btn-primary">add topic</button>
        {% endbuttons %}

    </form>

{% endblock content %}

</body>
</html>

learning_blog/learning_blogs/templates/learning_blogs/topic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Topic</title>
</head>
<body>
{% extends 'learning_blogs/base.html' %}

{% block header %}
    <h2>{{ topic }}</h2>
{% endblock header %}

{% block content %}
    <p>
        <a href="{% url 'learning_blogs:new_entry' topic.id %}">add new entry</a>
    </p>

    {% for entry in entries %}
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3>
                    {{ entry.date_added|date:'M d, Y H:i' }}
                    <small>
                        <a href="{% url 'learning_blogs:edit_entry' entry.id %}">
                            edit entry</a>
                    </small>
                </h3>
            </div>
            <div class="panel-body">
                {{ entry.text|linebreaks }}
            </div>
        </div> <!-- panel -->
    {% empty %}
        There are no entries for this topic yet.
    {% endfor %}

{% endblock content %}
</body>
</html>

learning_blog/learning_blogs/templates/learning_blogs/topics.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Topics</title>
</head>
<body>

{% extends 'learning_blogs/base.html' %}

{% block header %}
    <h1>Topics</h1>
{% endblock header %}

{% block content %}

    <ul>
        {% for topic in topics %}
            <li>
                <h3>
                    <a href="{% url 'learning_blogs:topic' topic.id %}">{{ topic }}</a>
                </h3>
            </li>
        {% empty %}
            <li>No topic have been added yet.</li>
        {% endfor %}
    </ul>

    <h3>
        <a href="{% url 'learning_blogs:new_topic' %}">Add a new topic</a>
    </h3>

{% endblock content %}

</body>
</html>